import type { Deal, Software, Reward, BannerDeal } from './types';
import { BadgePercent, Ticket, Wallpaper } from 'lucide-react';
import { GemIcon } from '@/components/icons/pixel-icons';

export const mockBanners: BannerDeal[] = [
  {
    id: 'b1',
    gameTitle: 'Elden Ring',
    imageUrl: 'https://placehold.co/1200x400.png',
    tagline: 'Become the Elden Lord. Now at its historic lowest price!',
    link: '/games/3',
  },
  {
    id: 'b2',
    gameTitle: 'Indie Gems Bundle',
    imageUrl: 'https://placehold.co/1200x400.png',
    tagline: 'Discover hidden treasures with our curated indie collection.',
    link: '/',
  },
  {
    id: 'b3',
    gameTitle: 'Cyberpunk 2077',
    imageUrl: 'https://placehold.co/1200x400.png',
    tagline: 'Wake up, Samurai. We have a city to burn. 50% off!',
    link: '/games/1',
  }
];

export const mockDeals: Deal[] = [
  {
    id: '1',
    gameTitle: 'Cyberpunk 2077',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.',
    discount: 50,
    priceINR: 1499,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Steam',
    isKeyshop: false,
    votes: 125,
    comments: 42,
    category: 'AAA',
    priceHistory: [
      { date: '2024-01-15', priceINR: 2999 },
      { date: '2024-02-20', priceINR: 2499 },
      { date: '2024-03-10', priceINR: 1799 },
      { date: '2024-04-25', priceINR: 1499 },
      { date: '2024-05-30', priceINR: 1999 },
    ],
    otherStores: [
      { storeName: 'GOG', storeLogoUrl: 'https://placehold.co/100x40.png', priceINR: 1599, dealLink: '#' },
      { storeName: 'Epic Games', storeLogoUrl: 'https://placehold.co/100x40.png', priceINR: 2999, dealLink: '#' },
      { storeName: 'GreenManGaming', storeLogoUrl: 'https://placehold.co/100x40.png', priceINR: 1450, dealLink: '#' }
    ]
  },
  {
    id: '2',
    gameTitle: 'Baldur\'s Gate 3',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.',
    discount: 10,
    priceINR: 2699,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'GOG',
    isKeyshop: false,
    votes: 302,
    comments: 89,
    isHistoricLow: true,
    category: 'AAA',
     priceHistory: [
      { date: '2024-01-15', priceINR: 2999 },
      { date: '2024-02-20', priceINR: 2999 },
      { date: '2024-03-10', priceINR: 2899 },
      { date: '2024-04-25', priceINR: 2699 },
      { date: '2024-05-30', priceINR: 2799 },
    ],
    otherStores: [
      { storeName: 'Steam', storeLogoUrl: 'https://placehold.co/100x40.png', priceINR: 2699, dealLink: '#' },
    ]
  },
  {
    id: '3',
    gameTitle: 'Elden Ring',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    discount: 75,
    priceINR: 899,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'GreenManGaming',
    isKeyshop: true,
    keyshopRiskLevel: 2,
    votes: 45,
    comments: 12,
    category: 'AAA',
  },
  {
    id: '4',
    gameTitle: 'Stardew Valley',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.',
    discount: 25,
    priceINR: 359,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Steam',
    isKeyshop: false,
    votes: 512,
    comments: 150,
    category: 'indie',
  },
   {
    id: '5',
    gameTitle: 'The Witcher 3',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'As Geralt of Rivia, a monster slayer for hire, you must find the Child of Prophecy, a living weapon that can alter the shape of the world.',
    discount: 80,
    priceINR: 200,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Kinguin',
    isKeyshop: true,
    keyshopRiskLevel: 4,
    votes: 88,
    comments: 31,
    category: 'AAA',
  },
   {
    id: '6',
    gameTitle: 'Hades',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.',
    discount: 50,
    priceINR: 284,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Epic Games',
    isKeyshop: false,
    votes: 210,
    comments: 77,
    category: 'indie',
  },
  {
    id: '7',
    gameTitle: 'Humble Choice',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'A monthly subscription bundle of PC games from Humble Bundle.',
    discount: 0,
    priceINR: 999,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Humble Bundle',
    isKeyshop: false,
    votes: 150,
    comments: 60,
    category: 'bundle',
  },
  {
    id: '8',
    gameTitle: 'Fanatical Platinum Collection',
    boxArtUrl: 'https://placehold.co/300x400.png',
    description: 'Build your own bundle from a selection of platinum-rated Steam games.',
    discount: 0,
    priceINR: 829,
    storeLogoUrl: 'https://placehold.co/100x40.png',
    storeName: 'Fanatical',
    isKeyshop: false,
    votes: 95,
    comments: 25,
    category: 'bundle',
  },
];

export const mockSoftware: Software[] = [
    { id: 's1', name: 'PixelOS Pro', imageUrl: 'https://placehold.co/300x200.png', priceINR: 4999, description: 'The ultimate pixel-perfect operating system for creators.' },
    { id: 's2', name: 'Chiptune Composer', imageUrl: 'https://placehold.co/300x200.png', priceINR: 2499, description: 'Create authentic 8-bit and 16-bit soundtracks.' },
    { id: 's3', name: 'SpriteVault', imageUrl: 'https://placehold.co/300x200.png', priceINR: 1999, description: 'A massive library of retro game assets.' },
    { id: 's4', name: 'RetroFilter Suite', imageUrl: 'https://placehold.co/300x200.png', priceINR: 999, description: 'Apply CRT and pixelation effects to any image.' },
];

export const mockRewards: Reward[] = [
    { id: 'r1', title: '10% Off Coupon', cost: 500, icon: BadgePercent },
    { id: 'r2', title: 'Exclusive Wallpaper', cost: 100, icon: Wallpaper },
    { id: 'r3', title: 'Raffle Ticket', cost: 50, icon: Ticket },
    { id: 'r4', title: 'Premium Avatar', cost: 1000, icon: GemIcon },
];
